sudo: required

language: rust

addons:
  apt:
    packages:
    - libasound2-dev
    - libsdl2-dev

cache:
  directories:
    - "/home/travis/.cache/sccache"

os:
- linux
- osx
- windows

rust:
- stable
- beta
- nightly

matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly

branches:
  only:
  - staging
  - trying
  - ci/use-sccache

before_install:
- ./.ci/travis/before_install.sh

before_script:
- export PATH=$PATH:/home/travis/.cargo/bin
- export RUSTFLAGS="-D warnings"
- export RUSTC_WRAPPER="./sccache"
- export SCCACHE_DIR="/home/travis/.cache/sccache"

# Generate documentation, compile the engine, run tests.
script:
- |
  echo "Build and test"
  cargo test --all || exit 1
- |
  if [ ${TRAVIS_RUST_VERSION} == "stable" ] && [ ${TRAVIS_OS_NAME} == "linux" ]
  then
    echo "Test book"
    ./mdbook test book -L target/debug/deps
  fi
- |
  if [ ${TRAVIS_RUST_VERSION} == "stable" ]
  then
    echo "Check common features"
    cargo check --all --features sdl_controller,profiler
  fi
